name: "Integration test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    services:
      oranc:
        image: ghcr.io/linyinfeng/oranc
        env:
          EXTRA_ARGS: --no-ssl
      registry:
        image: registry
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Get container ips
        id: get-ips
        run: |
          oranc_server_ip=$(docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' '${{ job.services.oranc.id }}')
          registry_ip=$(docker inspect --format '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' '${{ job.services.registry.id }}')
          echo "registry-ip=$registry_ip" >> "$GITHUB_OUTPUT"
          echo "oranc-server-ip=$oranc_server_ip" >> "$GITHUB_OUTPUT"
      - name: Generate signing key
        id: generate-key
        run: echo "signing-key=$(nix key generate-secret --key-name "oranc-test")" >> "$GITHUB_OUTPUT"
      - name: Verify
        uses: gacts/run-and-post-run@v1
        with:
          run: echo "do nothing, post action run after oranc's post action"
          post: |
            substituter_url="http://${{ steps.get-ips.outputs.oranc-server-ip }}/${{ steps.get-ips.outputs.registry-ip }}:5000/${{ github.repository_owner }}/oranc-cache" ; \
            echo "substituter url = $substituter_url" ; \
            nix store verify \
              --file ./test \
              --store "$substituter_url" \
              --eval-store auto \
              --sigs-needed 1
      - name: Setup oranc
        uses: ./
        with:
          orancServerContainer: ${{ job.services.oranc.id }}
          orancCli: github:linyinfeng/oranc
          signingKey: ${{ steps.generate-key.outputs.signing-key }}
          registry: ${{ steps.get-ips.outputs.registry-ip }}:5000
          orancCliExtraArgs: --no-ssl
          initialize: true
      - name: Build
        run: |
          nix build --file ./test
  test-ghcr-readonly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # do not push anything
      # packages: write
    services:
      oranc:
        image: ghcr.io/linyinfeng/oranc
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install nix
        uses: cachix/install-nix-action@master
        with:
          github_access_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Generate signing key
        id: generate-key
        run: echo "signing-key=$(nix key generate-secret --key-name "oranc-test")" >> "$GITHUB_OUTPUT"
      - name: Setup oranc
        uses: ./
        with:
          orancServerContainer: "${{ job.services.oranc.id }}"
          signingKey: ${{ steps.generate-key.outputs.signing-key }}
